// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMSAPI1.Data;

namespace TMSAPI1.Migrations
{
    [DbContext(typeof(TMSAPI1Context))]
    [Migration("20210625103730_aneesha")]
    partial class aneesha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TMSAPI.Models.Admininfo", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admininfo");
                });

            modelBuilder.Entity("TMSAPI.Models.allocatevehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("vehicleallocationtopassenger")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("allocatevehicle");
                });

            modelBuilder.Entity("TMSAPI.Models.employeeinfo", b =>
                {
                    b.Property<int>("employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vehicleID")
                        .HasColumnType("int");

                    b.HasKey("employeeid");

                    b.ToTable("employeeinfo");
                });

            modelBuilder.Entity("TMSAPI.Models.login", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("login");
                });

            modelBuilder.Entity("TMSAPI.Models.modify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("employee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("routeinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("modify");
                });

            modelBuilder.Entity("TMSAPI.Models.routeinformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("rootnumber")
                        .HasColumnType("int");

                    b.Property<string>("stops")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vehiclenumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("routeinformation");
                });

            modelBuilder.Entity("TMSAPI.Models.userregistration", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("userregistration");
                });

            modelBuilder.Entity("TMSAPI.Models.vehicleinformation", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("operable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("seat")
                        .HasColumnType("int");

                    b.Property<int>("vehiclenumber")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.ToTable("vehicleinformation");
                });
#pragma warning restore 612, 618
        }
    }
}
